### ISSUE TITLE
Script does not run

### ISSUE THREAD

**Issue by Bhlynd** [Steambot33/HiveOS-Nvidia-autofans#1]
Hi,

When I execute your script it stops at the below. I left it for a while but nothing happens.

root@frobisher:~# ./autofan.sh 
Found 5 GPU(s), Delay 10s
19/05/18 00:10:02
^C
root@frobisher:~# ^C

Tested on 2 x 1060, 1 x 1080 and 2 x 1070.

Cheers.
B

**Comment by Bhlynd** [comment]
Figured out the issue. 

The response from the nvidia commands takes excessively long on my rig. Example.

root@frobisher:~# time nvidia-settings -t -q [gpu:0]/GPUFanControlState      
1

real    0m24.263s
user    0m0.032s
sys     0m0.432s
root@frobisher:~#

This has a knock on effect with everything else.

**Comment by anton-kuptsov** [comment]
You using HiveOS or something other?

**Comment by Bhlynd** [comment]
Yes.

root@frobisher:~# uname -a
Linux frobisher 4.10.17-hiveos #1 SMP Sun Dec 10 08:48:43 EET 2017 x86_64 x86_64 x86_64 GNU/Linux
root@frobisher:~#

**Comment by anton-kuptsov** [comment]
may be : Once you are in run sudo -s to become root user. Start or stop miners, agent, etc only from root user.

**Comment by Bhlynd** [comment]
I have worked around the issue by doing the following.

-Removing the GPUFanControlState check. By default this should be enabled in hiveos.
-Running the script per GPU, these means hard coding the GPU with several screen sessions.

**Comment by Bhlynd** [comment]
Looking at your fan speed calc it doesn't take into account the min/max temp.

For anything below max temp the formula should look like

=B8*((B8-B1)*4+B4)/100

For anything equal or greater 

=B16*((B16-B1)*4+B5)/100

This will give you the correct fan speed information

**Comment by anton-kuptsov** [comment]
I do not know what you did, but it all works by default in any HiveOS builds. 
Regards.
