### ISSUE TITLE
Limit fan speed to 100%

### ISSUE THREAD

**Issue by WayneCollins** [Steambot33/HiveOS-Nvidia-autofans#2]
Depending on settings for min,max, and the coefs it is possible for the script to try to set a speed higher than 100% which fails, leaving the fan at a slower speed.
I think pull requests are disabled on your repo so the updated autofan
[autofan.txt](https://github.com/Steambot33/HiveOS-Nvidia-autofans/files/2019416/autofan.txt)
 file is attached.
Thanks for putting this together!
Wayne

**Comment by anton-kuptsov** [comment]
Thank you! 
It's TRUE, but the probability is very low.
Added!
